// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"
)

type CreateSkillBadRequest Error

func (*CreateSkillBadRequest) createSkillRes() {}

type CreateSkillConflict Error

func (*CreateSkillConflict) createSkillRes() {}

// DeleteSkillNoContent is response for DeleteSkill operation.
type DeleteSkillNoContent struct{}

func (*DeleteSkillNoContent) deleteSkillRes() {}

// DeleteTokenNoContent is response for DeleteToken operation.
type DeleteTokenNoContent struct{}

func (*DeleteTokenNoContent) deleteTokenRes() {}

// Ref: #/components/schemas/Error
type Error struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

func (*Error) createTokenRes() {}
func (*Error) deleteSkillRes() {}
func (*Error) deleteTokenRes() {}
func (*Error) getSkillRes()    {}

// Arbitrary string key-value metadata (SKILL.md frontmatter).
// Ref: #/components/schemas/Metadata
type Metadata map[string]string

func (s *Metadata) init() Metadata {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// NewNilDateTime returns new NilDateTime with value set to v.
func NewNilDateTime(v time.Time) NilDateTime {
	return NilDateTime{
		Value: v,
	}
}

// NilDateTime is nullable time.Time.
type NilDateTime struct {
	Value time.Time
	Null  bool
}

// SetTo sets value to v.
func (o *NilDateTime) SetTo(v time.Time) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilDateTime) SetToNull() {
	o.Null = true
	var v time.Time
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Merged schema.
// Ref: #/components/schemas/Skill
type Skill struct {
	ID            int64     `json:"id"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	License       string    `json:"license"`
	Compatibility string    `json:"compatibility"`
	AllowedTools  string    `json:"allowedTools"`
	Metadata      Metadata  `json:"metadata"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
	Body          string    `json:"body"`
}

// GetID returns the value of ID.
func (s *Skill) GetID() int64 {
	return s.ID
}

// GetName returns the value of Name.
func (s *Skill) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *Skill) GetDescription() string {
	return s.Description
}

// GetLicense returns the value of License.
func (s *Skill) GetLicense() string {
	return s.License
}

// GetCompatibility returns the value of Compatibility.
func (s *Skill) GetCompatibility() string {
	return s.Compatibility
}

// GetAllowedTools returns the value of AllowedTools.
func (s *Skill) GetAllowedTools() string {
	return s.AllowedTools
}

// GetMetadata returns the value of Metadata.
func (s *Skill) GetMetadata() Metadata {
	return s.Metadata
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Skill) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Skill) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// GetBody returns the value of Body.
func (s *Skill) GetBody() string {
	return s.Body
}

// SetID sets the value of ID.
func (s *Skill) SetID(val int64) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Skill) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *Skill) SetDescription(val string) {
	s.Description = val
}

// SetLicense sets the value of License.
func (s *Skill) SetLicense(val string) {
	s.License = val
}

// SetCompatibility sets the value of Compatibility.
func (s *Skill) SetCompatibility(val string) {
	s.Compatibility = val
}

// SetAllowedTools sets the value of AllowedTools.
func (s *Skill) SetAllowedTools(val string) {
	s.AllowedTools = val
}

// SetMetadata sets the value of Metadata.
func (s *Skill) SetMetadata(val Metadata) {
	s.Metadata = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Skill) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Skill) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// SetBody sets the value of Body.
func (s *Skill) SetBody(val string) {
	s.Body = val
}

func (*Skill) createSkillRes() {}
func (*Skill) getSkillRes()    {}
func (*Skill) updateSkillRes() {}

// Ref: #/components/schemas/SkillSummary
type SkillSummary struct {
	ID            int64     `json:"id"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	License       string    `json:"license"`
	Compatibility string    `json:"compatibility"`
	AllowedTools  string    `json:"allowedTools"`
	Metadata      Metadata  `json:"metadata"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *SkillSummary) GetID() int64 {
	return s.ID
}

// GetName returns the value of Name.
func (s *SkillSummary) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *SkillSummary) GetDescription() string {
	return s.Description
}

// GetLicense returns the value of License.
func (s *SkillSummary) GetLicense() string {
	return s.License
}

// GetCompatibility returns the value of Compatibility.
func (s *SkillSummary) GetCompatibility() string {
	return s.Compatibility
}

// GetAllowedTools returns the value of AllowedTools.
func (s *SkillSummary) GetAllowedTools() string {
	return s.AllowedTools
}

// GetMetadata returns the value of Metadata.
func (s *SkillSummary) GetMetadata() Metadata {
	return s.Metadata
}

// GetCreatedAt returns the value of CreatedAt.
func (s *SkillSummary) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *SkillSummary) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *SkillSummary) SetID(val int64) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *SkillSummary) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *SkillSummary) SetDescription(val string) {
	s.Description = val
}

// SetLicense sets the value of License.
func (s *SkillSummary) SetLicense(val string) {
	s.License = val
}

// SetCompatibility sets the value of Compatibility.
func (s *SkillSummary) SetCompatibility(val string) {
	s.Compatibility = val
}

// SetAllowedTools sets the value of AllowedTools.
func (s *SkillSummary) SetAllowedTools(val string) {
	s.AllowedTools = val
}

// SetMetadata sets the value of Metadata.
func (s *SkillSummary) SetMetadata(val Metadata) {
	s.Metadata = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *SkillSummary) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *SkillSummary) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// Editable skill fields. Optional string fields use empty string for "unset".
// Ref: #/components/schemas/SkillWrite
type SkillWrite struct {
	// Skill name = directory name. Lowercase a-z0-9 and hyphens, max 64 chars.
	Name        string `json:"name"`
	Description string `json:"description"`
	// SKILL.md markdown body after frontmatter.
	Body          string   `json:"body"`
	License       string   `json:"license"`
	Compatibility string   `json:"compatibility"`
	AllowedTools  string   `json:"allowedTools"`
	Metadata      Metadata `json:"metadata"`
}

// GetName returns the value of Name.
func (s *SkillWrite) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *SkillWrite) GetDescription() string {
	return s.Description
}

// GetBody returns the value of Body.
func (s *SkillWrite) GetBody() string {
	return s.Body
}

// GetLicense returns the value of License.
func (s *SkillWrite) GetLicense() string {
	return s.License
}

// GetCompatibility returns the value of Compatibility.
func (s *SkillWrite) GetCompatibility() string {
	return s.Compatibility
}

// GetAllowedTools returns the value of AllowedTools.
func (s *SkillWrite) GetAllowedTools() string {
	return s.AllowedTools
}

// GetMetadata returns the value of Metadata.
func (s *SkillWrite) GetMetadata() Metadata {
	return s.Metadata
}

// SetName sets the value of Name.
func (s *SkillWrite) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *SkillWrite) SetDescription(val string) {
	s.Description = val
}

// SetBody sets the value of Body.
func (s *SkillWrite) SetBody(val string) {
	s.Body = val
}

// SetLicense sets the value of License.
func (s *SkillWrite) SetLicense(val string) {
	s.License = val
}

// SetCompatibility sets the value of Compatibility.
func (s *SkillWrite) SetCompatibility(val string) {
	s.Compatibility = val
}

// SetAllowedTools sets the value of AllowedTools.
func (s *SkillWrite) SetAllowedTools(val string) {
	s.AllowedTools = val
}

// SetMetadata sets the value of Metadata.
func (s *SkillWrite) SetMetadata(val Metadata) {
	s.Metadata = val
}

// Ref: #/components/schemas/Token
type Token struct {
	ID    int64  `json:"id"`
	Label string `json:"label"`
	// First characters of the token for identification.
	Prefix     string      `json:"prefix"`
	LastUsedAt NilDateTime `json:"lastUsedAt"`
	CreatedAt  time.Time   `json:"createdAt"`
}

// GetID returns the value of ID.
func (s *Token) GetID() int64 {
	return s.ID
}

// GetLabel returns the value of Label.
func (s *Token) GetLabel() string {
	return s.Label
}

// GetPrefix returns the value of Prefix.
func (s *Token) GetPrefix() string {
	return s.Prefix
}

// GetLastUsedAt returns the value of LastUsedAt.
func (s *Token) GetLastUsedAt() NilDateTime {
	return s.LastUsedAt
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Token) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *Token) SetID(val int64) {
	s.ID = val
}

// SetLabel sets the value of Label.
func (s *Token) SetLabel(val string) {
	s.Label = val
}

// SetPrefix sets the value of Prefix.
func (s *Token) SetPrefix(val string) {
	s.Prefix = val
}

// SetLastUsedAt sets the value of LastUsedAt.
func (s *Token) SetLastUsedAt(val NilDateTime) {
	s.LastUsedAt = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Token) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// Merged schema.
// Ref: #/components/schemas/TokenCreated
type TokenCreated struct {
	ID    int64  `json:"id"`
	Label string `json:"label"`
	// First characters of the token for identification.
	Prefix     string      `json:"prefix"`
	LastUsedAt NilDateTime `json:"lastUsedAt"`
	CreatedAt  time.Time   `json:"createdAt"`
	// Plaintext token; shown only at creation.
	Token string `json:"token"`
}

// GetID returns the value of ID.
func (s *TokenCreated) GetID() int64 {
	return s.ID
}

// GetLabel returns the value of Label.
func (s *TokenCreated) GetLabel() string {
	return s.Label
}

// GetPrefix returns the value of Prefix.
func (s *TokenCreated) GetPrefix() string {
	return s.Prefix
}

// GetLastUsedAt returns the value of LastUsedAt.
func (s *TokenCreated) GetLastUsedAt() NilDateTime {
	return s.LastUsedAt
}

// GetCreatedAt returns the value of CreatedAt.
func (s *TokenCreated) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetToken returns the value of Token.
func (s *TokenCreated) GetToken() string {
	return s.Token
}

// SetID sets the value of ID.
func (s *TokenCreated) SetID(val int64) {
	s.ID = val
}

// SetLabel sets the value of Label.
func (s *TokenCreated) SetLabel(val string) {
	s.Label = val
}

// SetPrefix sets the value of Prefix.
func (s *TokenCreated) SetPrefix(val string) {
	s.Prefix = val
}

// SetLastUsedAt sets the value of LastUsedAt.
func (s *TokenCreated) SetLastUsedAt(val NilDateTime) {
	s.LastUsedAt = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *TokenCreated) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetToken sets the value of Token.
func (s *TokenCreated) SetToken(val string) {
	s.Token = val
}

func (*TokenCreated) createTokenRes() {}

// Ref: #/components/schemas/TokenWrite
type TokenWrite struct {
	Label string `json:"label"`
}

// GetLabel returns the value of Label.
func (s *TokenWrite) GetLabel() string {
	return s.Label
}

// SetLabel sets the value of Label.
func (s *TokenWrite) SetLabel(val string) {
	s.Label = val
}

type UpdateSkillBadRequest Error

func (*UpdateSkillBadRequest) updateSkillRes() {}

type UpdateSkillConflict Error

func (*UpdateSkillConflict) updateSkillRes() {}

type UpdateSkillNotFound Error

func (*UpdateSkillNotFound) updateSkillRes() {}
