// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateGeneration implements createGeneration operation.
	//
	// Start asynchronous skill generation from a raw idea. The job runs in the background; poll GET
	// /generate/{id} for the result. Disabled unless the LLM API key is configured at startup.
	//
	// POST /generate
	CreateGeneration(ctx context.Context, req *GenerationWrite) (CreateGenerationRes, error)
	// CreateSkill implements createSkill operation.
	//
	// Create a skill.
	//
	// POST /skills
	CreateSkill(ctx context.Context, req *SkillWrite) (CreateSkillRes, error)
	// CreateToken implements createToken operation.
	//
	// Create a mount token. The plaintext token is returned once.
	//
	// POST /tokens
	CreateToken(ctx context.Context, req *TokenWrite) (CreateTokenRes, error)
	// DeleteSkill implements deleteSkill operation.
	//
	// Delete a skill.
	//
	// DELETE /skills/{id}
	DeleteSkill(ctx context.Context, params DeleteSkillParams) (DeleteSkillRes, error)
	// DeleteToken implements deleteToken operation.
	//
	// Revoke a mount token.
	//
	// DELETE /tokens/{id}
	DeleteToken(ctx context.Context, params DeleteTokenParams) (DeleteTokenRes, error)
	// GetConfig implements getConfig operation.
	//
	// Non-secret server configuration, e.g. whether skill generation is enabled.
	//
	// GET /config
	GetConfig(ctx context.Context) (*ServerConfig, error)
	// GetGeneration implements getGeneration operation.
	//
	// Get the state of a generation job.
	//
	// GET /generate/{id}
	GetGeneration(ctx context.Context, params GetGenerationParams) (GetGenerationRes, error)
	// GetSkill implements getSkill operation.
	//
	// Get a single skill including its body.
	//
	// GET /skills/{id}
	GetSkill(ctx context.Context, params GetSkillParams) (GetSkillRes, error)
	// ListSkills implements listSkills operation.
	//
	// List all skills, newest metadata only (no bodies).
	//
	// GET /skills
	ListSkills(ctx context.Context) ([]SkillSummary, error)
	// ListTokens implements listTokens operation.
	//
	// List all mount tokens (no secrets).
	//
	// GET /tokens
	ListTokens(ctx context.Context) ([]Token, error)
	// UpdateSkill implements updateSkill operation.
	//
	// Replace all editable fields of a skill.
	//
	// PUT /skills/{id}
	UpdateSkill(ctx context.Context, req *SkillWrite, params UpdateSkillParams) (UpdateSkillRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
