// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateGenerationOperation OperationName = "CreateGeneration"
	CreateSkillOperation      OperationName = "CreateSkill"
	CreateTokenOperation      OperationName = "CreateToken"
	DeleteSkillOperation      OperationName = "DeleteSkill"
	DeleteTokenOperation      OperationName = "DeleteToken"
	GetConfigOperation        OperationName = "GetConfig"
	GetGenerationOperation    OperationName = "GetGeneration"
	GetSkillOperation         OperationName = "GetSkill"
	ListSkillsOperation       OperationName = "ListSkills"
	ListTokensOperation       OperationName = "ListTokens"
	UpdateSkillOperation      OperationName = "UpdateSkill"
)
