// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/go-faster/errors"
)

type CreateSkillBadRequest Error

func (*CreateSkillBadRequest) createSkillRes() {}

type CreateSkillConflict Error

func (*CreateSkillConflict) createSkillRes() {}

// DeleteSkillNoContent is response for DeleteSkill operation.
type DeleteSkillNoContent struct{}

func (*DeleteSkillNoContent) deleteSkillRes() {}

// DeleteTokenNoContent is response for DeleteToken operation.
type DeleteTokenNoContent struct{}

func (*DeleteTokenNoContent) deleteTokenRes() {}

// Ref: #/components/schemas/Error
type Error struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

func (*Error) createGenerationRes() {}
func (*Error) createTokenRes()      {}
func (*Error) deleteSkillRes()      {}
func (*Error) deleteTokenRes()      {}
func (*Error) getGenerationRes()    {}
func (*Error) getSkillRes()         {}

// Ref: #/components/schemas/Generation
type Generation struct {
	ID     string           `json:"id"`
	Status GenerationStatus `json:"status"`
	// Human-readable failure reason when status is error.
	Error OptString `json:"error"`
	// Created skill id when status is done.
	SkillId OptInt64 `json:"skillId"`
	// Created skill name when status is done.
	SkillName OptString `json:"skillName"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *Generation) GetID() string {
	return s.ID
}

// GetStatus returns the value of Status.
func (s *Generation) GetStatus() GenerationStatus {
	return s.Status
}

// GetError returns the value of Error.
func (s *Generation) GetError() OptString {
	return s.Error
}

// GetSkillId returns the value of SkillId.
func (s *Generation) GetSkillId() OptInt64 {
	return s.SkillId
}

// GetSkillName returns the value of SkillName.
func (s *Generation) GetSkillName() OptString {
	return s.SkillName
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Generation) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Generation) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Generation) SetID(val string) {
	s.ID = val
}

// SetStatus sets the value of Status.
func (s *Generation) SetStatus(val GenerationStatus) {
	s.Status = val
}

// SetError sets the value of Error.
func (s *Generation) SetError(val OptString) {
	s.Error = val
}

// SetSkillId sets the value of SkillId.
func (s *Generation) SetSkillId(val OptInt64) {
	s.SkillId = val
}

// SetSkillName sets the value of SkillName.
func (s *Generation) SetSkillName(val OptString) {
	s.SkillName = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Generation) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Generation) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

func (*Generation) getGenerationRes() {}

// Ref: #/components/schemas/GenerationCreated
type GenerationCreated struct {
	// Generation job id, usable with GET /generate/{id}.
	ID string `json:"id"`
}

// GetID returns the value of ID.
func (s *GenerationCreated) GetID() string {
	return s.ID
}

// SetID sets the value of ID.
func (s *GenerationCreated) SetID(val string) {
	s.ID = val
}

func (*GenerationCreated) createGenerationRes() {}

type GenerationStatus string

const (
	GenerationStatusRunning GenerationStatus = "running"
	GenerationStatusDone    GenerationStatus = "done"
	GenerationStatusError   GenerationStatus = "error"
)

// AllValues returns all GenerationStatus values.
func (GenerationStatus) AllValues() []GenerationStatus {
	return []GenerationStatus{
		GenerationStatusRunning,
		GenerationStatusDone,
		GenerationStatusError,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s GenerationStatus) MarshalText() ([]byte, error) {
	switch s {
	case GenerationStatusRunning:
		return []byte(s), nil
	case GenerationStatusDone:
		return []byte(s), nil
	case GenerationStatusError:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *GenerationStatus) UnmarshalText(data []byte) error {
	switch GenerationStatus(data) {
	case GenerationStatusRunning:
		*s = GenerationStatusRunning
		return nil
	case GenerationStatusDone:
		*s = GenerationStatusDone
		return nil
	case GenerationStatusError:
		*s = GenerationStatusError
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/GenerationWrite
type GenerationWrite struct {
	// Raw idea or draft to turn into a skill.
	Idea string `json:"idea"`
}

// GetIdea returns the value of Idea.
func (s *GenerationWrite) GetIdea() string {
	return s.Idea
}

// SetIdea sets the value of Idea.
func (s *GenerationWrite) SetIdea(val string) {
	s.Idea = val
}

// Arbitrary string key-value metadata (SKILL.md frontmatter).
// Ref: #/components/schemas/Metadata
type Metadata map[string]string

func (s *Metadata) init() Metadata {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// NewNilDateTime returns new NilDateTime with value set to v.
func NewNilDateTime(v time.Time) NilDateTime {
	return NilDateTime{
		Value: v,
	}
}

// NilDateTime is nullable time.Time.
type NilDateTime struct {
	Value time.Time
	Null  bool
}

// SetTo sets value to v.
func (o *NilDateTime) SetTo(v time.Time) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilDateTime) SetToNull() {
	o.Null = true
	var v time.Time
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptMetadata returns new OptMetadata with value set to v.
func NewOptMetadata(v Metadata) OptMetadata {
	return OptMetadata{
		Value: v,
		Set:   true,
	}
}

// OptMetadata is optional Metadata.
type OptMetadata struct {
	Value Metadata
	Set   bool
}

// IsSet returns true if OptMetadata was set.
func (o OptMetadata) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptMetadata) Reset() {
	var v Metadata
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptMetadata) SetTo(v Metadata) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptMetadata) Get() (v Metadata, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptMetadata) Or(d Metadata) Metadata {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/ServerConfig
type ServerConfig struct {
	Llm ServerConfigLlm `json:"llm"`
}

// GetLlm returns the value of Llm.
func (s *ServerConfig) GetLlm() ServerConfigLlm {
	return s.Llm
}

// SetLlm sets the value of Llm.
func (s *ServerConfig) SetLlm(val ServerConfigLlm) {
	s.Llm = val
}

type ServerConfigLlm struct {
	// Whether agent-based skill generation is configured (LLM API key set at startup).
	Enabled bool `json:"enabled"`
	// Model used for generation.
	Model string `json:"model"`
}

// GetEnabled returns the value of Enabled.
func (s *ServerConfigLlm) GetEnabled() bool {
	return s.Enabled
}

// GetModel returns the value of Model.
func (s *ServerConfigLlm) GetModel() string {
	return s.Model
}

// SetEnabled sets the value of Enabled.
func (s *ServerConfigLlm) SetEnabled(val bool) {
	s.Enabled = val
}

// SetModel sets the value of Model.
func (s *ServerConfigLlm) SetModel(val string) {
	s.Model = val
}

// Merged schema.
// Ref: #/components/schemas/Skill
type Skill struct {
	ID            int64     `json:"id"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	License       string    `json:"license"`
	Compatibility string    `json:"compatibility"`
	AllowedTools  string    `json:"allowedTools"`
	Metadata      Metadata  `json:"metadata"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
	Body          string    `json:"body"`
}

// GetID returns the value of ID.
func (s *Skill) GetID() int64 {
	return s.ID
}

// GetName returns the value of Name.
func (s *Skill) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *Skill) GetDescription() string {
	return s.Description
}

// GetLicense returns the value of License.
func (s *Skill) GetLicense() string {
	return s.License
}

// GetCompatibility returns the value of Compatibility.
func (s *Skill) GetCompatibility() string {
	return s.Compatibility
}

// GetAllowedTools returns the value of AllowedTools.
func (s *Skill) GetAllowedTools() string {
	return s.AllowedTools
}

// GetMetadata returns the value of Metadata.
func (s *Skill) GetMetadata() Metadata {
	return s.Metadata
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Skill) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Skill) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// GetBody returns the value of Body.
func (s *Skill) GetBody() string {
	return s.Body
}

// SetID sets the value of ID.
func (s *Skill) SetID(val int64) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Skill) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *Skill) SetDescription(val string) {
	s.Description = val
}

// SetLicense sets the value of License.
func (s *Skill) SetLicense(val string) {
	s.License = val
}

// SetCompatibility sets the value of Compatibility.
func (s *Skill) SetCompatibility(val string) {
	s.Compatibility = val
}

// SetAllowedTools sets the value of AllowedTools.
func (s *Skill) SetAllowedTools(val string) {
	s.AllowedTools = val
}

// SetMetadata sets the value of Metadata.
func (s *Skill) SetMetadata(val Metadata) {
	s.Metadata = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Skill) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Skill) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// SetBody sets the value of Body.
func (s *Skill) SetBody(val string) {
	s.Body = val
}

func (*Skill) createSkillRes() {}
func (*Skill) getSkillRes()    {}
func (*Skill) updateSkillRes() {}

// Ref: #/components/schemas/SkillSummary
type SkillSummary struct {
	ID            int64     `json:"id"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	License       string    `json:"license"`
	Compatibility string    `json:"compatibility"`
	AllowedTools  string    `json:"allowedTools"`
	Metadata      Metadata  `json:"metadata"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *SkillSummary) GetID() int64 {
	return s.ID
}

// GetName returns the value of Name.
func (s *SkillSummary) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *SkillSummary) GetDescription() string {
	return s.Description
}

// GetLicense returns the value of License.
func (s *SkillSummary) GetLicense() string {
	return s.License
}

// GetCompatibility returns the value of Compatibility.
func (s *SkillSummary) GetCompatibility() string {
	return s.Compatibility
}

// GetAllowedTools returns the value of AllowedTools.
func (s *SkillSummary) GetAllowedTools() string {
	return s.AllowedTools
}

// GetMetadata returns the value of Metadata.
func (s *SkillSummary) GetMetadata() Metadata {
	return s.Metadata
}

// GetCreatedAt returns the value of CreatedAt.
func (s *SkillSummary) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *SkillSummary) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *SkillSummary) SetID(val int64) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *SkillSummary) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *SkillSummary) SetDescription(val string) {
	s.Description = val
}

// SetLicense sets the value of License.
func (s *SkillSummary) SetLicense(val string) {
	s.License = val
}

// SetCompatibility sets the value of Compatibility.
func (s *SkillSummary) SetCompatibility(val string) {
	s.Compatibility = val
}

// SetAllowedTools sets the value of AllowedTools.
func (s *SkillSummary) SetAllowedTools(val string) {
	s.AllowedTools = val
}

// SetMetadata sets the value of Metadata.
func (s *SkillSummary) SetMetadata(val Metadata) {
	s.Metadata = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *SkillSummary) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *SkillSummary) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// Editable skill fields. Optional fields may be omitted.
// Ref: #/components/schemas/SkillWrite
type SkillWrite struct {
	// Skill name = directory name. Lowercase a-z0-9 and hyphens, max 64 chars.
	Name        string `json:"name"`
	Description string `json:"description"`
	// SKILL.md markdown body after frontmatter.
	Body          string      `json:"body"`
	License       OptString   `json:"license"`
	Compatibility OptString   `json:"compatibility"`
	AllowedTools  OptString   `json:"allowedTools"`
	Metadata      OptMetadata `json:"metadata"`
}

// GetName returns the value of Name.
func (s *SkillWrite) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *SkillWrite) GetDescription() string {
	return s.Description
}

// GetBody returns the value of Body.
func (s *SkillWrite) GetBody() string {
	return s.Body
}

// GetLicense returns the value of License.
func (s *SkillWrite) GetLicense() OptString {
	return s.License
}

// GetCompatibility returns the value of Compatibility.
func (s *SkillWrite) GetCompatibility() OptString {
	return s.Compatibility
}

// GetAllowedTools returns the value of AllowedTools.
func (s *SkillWrite) GetAllowedTools() OptString {
	return s.AllowedTools
}

// GetMetadata returns the value of Metadata.
func (s *SkillWrite) GetMetadata() OptMetadata {
	return s.Metadata
}

// SetName sets the value of Name.
func (s *SkillWrite) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *SkillWrite) SetDescription(val string) {
	s.Description = val
}

// SetBody sets the value of Body.
func (s *SkillWrite) SetBody(val string) {
	s.Body = val
}

// SetLicense sets the value of License.
func (s *SkillWrite) SetLicense(val OptString) {
	s.License = val
}

// SetCompatibility sets the value of Compatibility.
func (s *SkillWrite) SetCompatibility(val OptString) {
	s.Compatibility = val
}

// SetAllowedTools sets the value of AllowedTools.
func (s *SkillWrite) SetAllowedTools(val OptString) {
	s.AllowedTools = val
}

// SetMetadata sets the value of Metadata.
func (s *SkillWrite) SetMetadata(val OptMetadata) {
	s.Metadata = val
}

// Ref: #/components/schemas/Token
type Token struct {
	ID    int64  `json:"id"`
	Label string `json:"label"`
	// First characters of the token for identification.
	Prefix     string      `json:"prefix"`
	LastUsedAt NilDateTime `json:"lastUsedAt"`
	CreatedAt  time.Time   `json:"createdAt"`
}

// GetID returns the value of ID.
func (s *Token) GetID() int64 {
	return s.ID
}

// GetLabel returns the value of Label.
func (s *Token) GetLabel() string {
	return s.Label
}

// GetPrefix returns the value of Prefix.
func (s *Token) GetPrefix() string {
	return s.Prefix
}

// GetLastUsedAt returns the value of LastUsedAt.
func (s *Token) GetLastUsedAt() NilDateTime {
	return s.LastUsedAt
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Token) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *Token) SetID(val int64) {
	s.ID = val
}

// SetLabel sets the value of Label.
func (s *Token) SetLabel(val string) {
	s.Label = val
}

// SetPrefix sets the value of Prefix.
func (s *Token) SetPrefix(val string) {
	s.Prefix = val
}

// SetLastUsedAt sets the value of LastUsedAt.
func (s *Token) SetLastUsedAt(val NilDateTime) {
	s.LastUsedAt = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Token) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// Merged schema.
// Ref: #/components/schemas/TokenCreated
type TokenCreated struct {
	ID    int64  `json:"id"`
	Label string `json:"label"`
	// First characters of the token for identification.
	Prefix     string      `json:"prefix"`
	LastUsedAt NilDateTime `json:"lastUsedAt"`
	CreatedAt  time.Time   `json:"createdAt"`
	// Plaintext token; shown only at creation.
	Token string `json:"token"`
}

// GetID returns the value of ID.
func (s *TokenCreated) GetID() int64 {
	return s.ID
}

// GetLabel returns the value of Label.
func (s *TokenCreated) GetLabel() string {
	return s.Label
}

// GetPrefix returns the value of Prefix.
func (s *TokenCreated) GetPrefix() string {
	return s.Prefix
}

// GetLastUsedAt returns the value of LastUsedAt.
func (s *TokenCreated) GetLastUsedAt() NilDateTime {
	return s.LastUsedAt
}

// GetCreatedAt returns the value of CreatedAt.
func (s *TokenCreated) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetToken returns the value of Token.
func (s *TokenCreated) GetToken() string {
	return s.Token
}

// SetID sets the value of ID.
func (s *TokenCreated) SetID(val int64) {
	s.ID = val
}

// SetLabel sets the value of Label.
func (s *TokenCreated) SetLabel(val string) {
	s.Label = val
}

// SetPrefix sets the value of Prefix.
func (s *TokenCreated) SetPrefix(val string) {
	s.Prefix = val
}

// SetLastUsedAt sets the value of LastUsedAt.
func (s *TokenCreated) SetLastUsedAt(val NilDateTime) {
	s.LastUsedAt = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *TokenCreated) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetToken sets the value of Token.
func (s *TokenCreated) SetToken(val string) {
	s.Token = val
}

func (*TokenCreated) createTokenRes() {}

// Ref: #/components/schemas/TokenWrite
type TokenWrite struct {
	Label string `json:"label"`
}

// GetLabel returns the value of Label.
func (s *TokenWrite) GetLabel() string {
	return s.Label
}

// SetLabel sets the value of Label.
func (s *TokenWrite) SetLabel(val string) {
	s.Label = val
}

type UpdateSkillBadRequest Error

func (*UpdateSkillBadRequest) updateSkillRes() {}

type UpdateSkillConflict Error

func (*UpdateSkillConflict) updateSkillRes() {}

type UpdateSkillNotFound Error

func (*UpdateSkillNotFound) updateSkillRes() {}
