// Code generated by ogen, DO NOT EDIT.
package api

type CreateSkillRes interface {
	createSkillRes()
}

type CreateTokenRes interface {
	createTokenRes()
}

type DeleteSkillRes interface {
	deleteSkillRes()
}

type DeleteTokenRes interface {
	deleteTokenRes()
}

type GetSkillRes interface {
	getSkillRes()
}

type UpdateSkillRes interface {
	updateSkillRes()
}
