// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateSkillOperation OperationName = "CreateSkill"
	CreateTokenOperation OperationName = "CreateToken"
	DeleteSkillOperation OperationName = "DeleteSkill"
	DeleteTokenOperation OperationName = "DeleteToken"
	GetSkillOperation    OperationName = "GetSkill"
	ListSkillsOperation  OperationName = "ListSkills"
	ListTokensOperation  OperationName = "ListTokens"
	UpdateSkillOperation OperationName = "UpdateSkill"
)
