// Package dbo provides the SQLite-backed persistence layer, generated by sqlc.
//
// NewFromFile opens (creating if absent) and migrates the database, returning a Queries.
// The single connection is kept open for the life of the process; for an in-memory
// database ("file::memory:...") this keeps the data alive, so the handler is exercised the
// same way in tests and smoke runs as with a file.
package dbo

import (
	"database/sql"
	"embed"
	"fmt"
	"io"

	migrate "github.com/rubenv/sql-migrate"
	_ "modernc.org/sqlite" // register the pure-Go SQLite driver as "sqlite"
)

//go:generate sqlc generate

//go:embed migrations
var migrations embed.FS

// NewFromFile opens the SQLite database at file, runs pending migrations, and returns a
// Queries bound to a single writer connection (SQLite serializes writes).
func NewFromFile(file string) (*Queries, error) {
	dsn := fmt.Sprintf("file:%s?_journal_mode=WAL&cache=shared&_pragma=foreign_keys(1)", file)
	db, err := sql.Open("sqlite", dsn)
	if err != nil {
		return nil, fmt.Errorf("open database: %w", err)
	}
	db.SetMaxIdleConns(1)
	db.SetMaxOpenConns(1)

	_, err = migrate.Exec(db, "sqlite3", &migrate.EmbedFileSystemMigrationSource{
		FileSystem: migrations,
		Root:       "migrations",
	}, migrate.Up)
	if err != nil {
		db.Close()
		return nil, fmt.Errorf("migrate db: %w", err)
	}

	return New(db), nil
}

// Close releases the underlying database connection, if the DBTX exposes one.
func (q *Queries) Close() error {
	if v, ok := q.db.(io.Closer); ok && v != nil {
		return v.Close()
	}
	return nil
}
