// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbo

import (
	"time"
)

type Skill struct {
	ID            int64     `json:"id"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	Body          string    `json:"body"`
	License       *string   `json:"license"`
	Compatibility *string   `json:"compatibility"`
	AllowedTools  *string   `json:"allowed_tools"`
	Metadata      string    `json:"metadata"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Token struct {
	ID          int64      `json:"id"`
	Label       string     `json:"label"`
	TokenHash   string     `json:"token_hash"`
	TokenPrefix string     `json:"token_prefix"`
	LastUsedAt  *time.Time `json:"last_used_at"`
	CreatedAt   time.Time  `json:"created_at"`
}
