// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skill.sql

package dbo

import (
	"context"
	"time"
)

const createSkill = `-- name: CreateSkill :one
INSERT INTO skill (name, description, body, license, compatibility, allowed_tools, metadata)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateSkillParams struct {
	Name          string `json:"name"`
	Description   string `json:"description"`
	Body          string `json:"body"`
	License       string `json:"license"`
	Compatibility string `json:"compatibility"`
	AllowedTools  string `json:"allowed_tools"`
	Metadata      string `json:"metadata"`
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createSkill,
		arg.Name,
		arg.Description,
		arg.Body,
		arg.License,
		arg.Compatibility,
		arg.AllowedTools,
		arg.Metadata,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteSkill = `-- name: DeleteSkill :execrows
DELETE FROM skill WHERE id = ?
`

func (q *Queries) DeleteSkill(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSkill, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSkill = `-- name: GetSkill :one
SELECT id, name, description, body, license, compatibility, allowed_tools, metadata, created_at, updated_at FROM skill WHERE id = ?
`

func (q *Queries) GetSkill(ctx context.Context, id int64) (Skill, error) {
	row := q.db.QueryRowContext(ctx, getSkill, id)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Body,
		&i.License,
		&i.Compatibility,
		&i.AllowedTools,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillByName = `-- name: GetSkillByName :one
SELECT id, name, description, body, license, compatibility, allowed_tools, metadata, created_at, updated_at FROM skill WHERE name = ?
`

func (q *Queries) GetSkillByName(ctx context.Context, name string) (Skill, error) {
	row := q.db.QueryRowContext(ctx, getSkillByName, name)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Body,
		&i.License,
		&i.Compatibility,
		&i.AllowedTools,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSkills = `-- name: ListSkills :many
SELECT id, name, description, license, compatibility, allowed_tools, metadata, created_at, updated_at
FROM skill
ORDER BY name
`

type ListSkillsRow struct {
	ID            int64     `json:"id"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	License       string    `json:"license"`
	Compatibility string    `json:"compatibility"`
	AllowedTools  string    `json:"allowed_tools"`
	Metadata      string    `json:"metadata"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// Summary without the (potentially large) body column.
func (q *Queries) ListSkills(ctx context.Context) ([]ListSkillsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSkillsRow{}
	for rows.Next() {
		var i ListSkillsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.License,
			&i.Compatibility,
			&i.AllowedTools,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSkill = `-- name: UpdateSkill :exec
UPDATE skill SET
    name = ?,
    description = ?,
    body = ?,
    license = ?,
    compatibility = ?,
    allowed_tools = ?,
    metadata = ?,
    updated_at = current_timestamp
WHERE id = ?
`

type UpdateSkillParams struct {
	Name          string `json:"name"`
	Description   string `json:"description"`
	Body          string `json:"body"`
	License       string `json:"license"`
	Compatibility string `json:"compatibility"`
	AllowedTools  string `json:"allowed_tools"`
	Metadata      string `json:"metadata"`
	ID            int64  `json:"id"`
}

func (q *Queries) UpdateSkill(ctx context.Context, arg UpdateSkillParams) error {
	_, err := q.db.ExecContext(ctx, updateSkill,
		arg.Name,
		arg.Description,
		arg.Body,
		arg.License,
		arg.Compatibility,
		arg.AllowedTools,
		arg.Metadata,
		arg.ID,
	)
	return err
}
