// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: token.sql

package dbo

import (
	"context"
)

const createToken = `-- name: CreateToken :one
INSERT INTO token (label, token_hash, token_prefix)
VALUES (?, ?, ?)
RETURNING id
`

type CreateTokenParams struct {
	Label       string `json:"label"`
	TokenHash   string `json:"token_hash"`
	TokenPrefix string `json:"token_prefix"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createToken, arg.Label, arg.TokenHash, arg.TokenPrefix)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteToken = `-- name: DeleteToken :execrows
DELETE FROM token WHERE id = ?
`

func (q *Queries) DeleteToken(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getToken = `-- name: GetToken :one
SELECT id, label, token_hash, token_prefix, last_used_at, created_at FROM token WHERE id = ?
`

func (q *Queries) GetToken(ctx context.Context, id int64) (Token, error) {
	row := q.db.QueryRowContext(ctx, getToken, id)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTokenByHash = `-- name: GetTokenByHash :one
SELECT id, label, token_hash, token_prefix, last_used_at, created_at FROM token WHERE token_hash = ?
`

func (q *Queries) GetTokenByHash(ctx context.Context, tokenHash string) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenByHash, tokenHash)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listTokens = `-- name: ListTokens :many
SELECT id, label, token_hash, token_prefix, last_used_at, created_at FROM token ORDER BY id DESC
`

func (q *Queries) ListTokens(ctx context.Context) ([]Token, error) {
	rows, err := q.db.QueryContext(ctx, listTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Token{}
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchToken = `-- name: TouchToken :exec
UPDATE token SET last_used_at = current_timestamp WHERE token_hash = ?
`

func (q *Queries) TouchToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, touchToken, tokenHash)
	return err
}
